apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
  labels: { app: survey-backend, team: SSSN }
spec:
  replicas: 2
  selector: { matchLabels: { app: survey-backend } }
  template:
    metadata:
      labels: { app: survey-backend }
    spec:
      containers:
        - name: api
          image: spotluru/sssn-survey-backend:1
          ports: [ { containerPort: 8000 } ]
          env:
            - { name: DB_HOST, value: "your-rds-endpoint.amazonaws.com" }
            - { name: DB_PORT, value: "3306" }
            - { name: DB_USER, value: "admin" }
            - { name: DB_PASS, value: "replace-me" }
            - { name: DB_NAME, value: "surveydb" }
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: survey-backend
  labels: { app: survey-backend }
spec:
  selector: { app: survey-backend }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
