apiVersion: v1
kind: ConfigMap
metadata:
  name: survey-frontend-nginx
  namespace: sssn
data:
  default.conf: |
    server {
      listen 80;

      # static site
      location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
      }

      # proxy API to backend Service (in-cluster DNS)
      location /api/ {
        proxy_pass http://survey-backend.sssn.svc.cluster.local:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
